name: Create macOS executable

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller
        
    - name: Run PyInstaller
      run: pyinstaller dictionary.spec
    
    - name: Install Git LFS
      run: |
        brew install git-lfs
        git lfs install
    
    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Create or switch to 'mac' branch
      run: |
        git fetch
        git checkout -B mac
    
    - name: Track dist directory with Git LFS
      run: |
        git lfs track "dist/**"
        git add .gitattributes
    
    - name: Add and commit 'dist' directory
      run: |
        git add dist -f
        git commit -m "Add macOS executable"
    
    - name: Push changes to 'mac' branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin mac --force
